### ISSUE TITLE
print '"POST {}"'.format(self.path) where second ' shows invalid syntax

### ISSUE THREAD

**Issue by i0brendan0** [yenatch/crowdmap#16]
Title basically says it all. I tried the command in both cygwin and command prompt and they both came back with a ^ under the second '.

**Comment by yenatch** [comment]
Thanks. This should be fixed by #17. Run `git pull` in your crowdmap repo and try again.

**Comment by i0brendan0** [comment]
Tells me I need to commit my changes or stash them before I merge. I have no clue what that means.

[EDIT] I'll just re-clone and move.

**Comment by i0brendan0** [comment]
Now it's not doing anything after I do python crowdmap/server.py. Yes crowdmap is inside my pokecrystal directory and yes I'm doing the command from the pokecrystal directory. After I press enter with the command it doesn't show anything after. I let the process through my firewall as a window popped up. But nothing happens.

**Comment by yenatch** [comment]
That's weird. If you start it and then go to http://127.0.0.1:8000/crowdmap what happens?

**Comment by i0brendan0** [comment]
I'll see when I get back to my computer. I'll let you know what happens.

**Comment by i0brendan0** [comment]
Olivine City is Shown. So it's working but it doesn't automatically pop up on a browser.

**Comment by i0brendan0** [comment]
So I'm trying to change Olivine City map and when I go to save it doesn't save the tiles, just the warp that I moved (the beta warp so I can add the fossil Pokemon :P). Am I supposed to wait?

Oh I'm on Firefox btw. And I guess it's not saving the warp either. Just looks like it does.

**Comment by yenatch** [comment]
No, probably a caching issue. Firefox is especially bad about it. Try Chrome (but it's not perfect either). Once the Electron port is finished these problems will go away (and there won't be a server).

I've also made it so that it opens in your default browser when you start the server. `git pull` again to get it.

**Comment by i0brendan0** [comment]
I hate chrome. Will Internet Explorer be acceptable?

**Comment by yenatch** [comment]
No, sorry. You may be able to use any chromium-based browser rather than Chrome, but I haven't tested.

**Comment by i0brendan0** [comment]
I don't know any other chromium browser. Ugh.

**Comment by i0brendan0** [comment]
Yeah so I tried with Chrome and it's still not working. I can try to save again and give you the stuff from cygwin.

**Comment by yenatch** [comment]
Sure. I would check the browser log as well (press F12).

**Comment by i0brendan0** [comment]
cygwin-Traceback (most recent call last):
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 681, in __init__
    self.handle()
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\http\server.py", line 422, in handle
    self.handle_one_request()
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\http\server.py", line 410, in handle_one_request
    method()
  File "crowdmap/server.py", line 30, in do_POST
    length = int(self.headers.getheader('content-length'))
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
Traceback (most recent call last):
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 341, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 354, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 681, in __init__
    self.handle()
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\http\server.py", line 422, in handle
    self.handle_one_request()
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\http\server.py", line 410, in handle_one_request
    method()
  File "crowdmap/server.py", line 30, in do_POST
    length = int(self.headers.getheader('content-length'))
AttributeError: 'HTTPMessage' object has no attribute 'getheader'
Traceback (most recent call last):
  File "C:\Users\Hansen\AppData\Local\Programs\Python\Python35-32\lib\socketserver.py", line 313, in _handle_request_noblock
    self.process_request(request, client_address)

I saved twice to make sure the lines got written to the console so that's why it's twice.
And I don't know how to check chrome's log. I pressed F12 but there's a bunch of stuff.

**Comment by i0brendan0** [comment]
Has there been any progress or do you still need a Chrome log?

**Comment by yenatch** [comment]
Caching issues are fixed and Firefox now works again.
